name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose --release
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: linux
        path: target/release/remote_start
  build_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose --release
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: windows
        path: target/release/remote_start.exe
        
